name: Build and Package Plugin

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3
      
    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '4.8.x'
        
    - name: Restore NuGet packages
      run: nuget restore PPGSage50Plugin.sln
      
    - name: Build solution
      run: msbuild PPGSage50Plugin.sln /p:Configuration=Release /p:Platform="Any CPU" /verbosity:minimal
      
    - name: Run tests
      run: msbuild PPGSage50Plugin.sln /p:Configuration=Release /p:Platform="Any CPU" /t:Test
      continue-on-error: true
      
    - name: Create distribution package
      run: |
        mkdir dist
        copy "bin\Release\PPGSage50Plugin.dll" "dist\"
        copy "bin\Release\PPGSage50Plugin.exe" "dist\"
        copy "PPGSage50Plugin\App.config" "dist\"
        copy "PPGSage50Plugin\log4net.config" "dist\"
        copy "packages\Newtonsoft.Json.13.0.3\lib\net45\Newtonsoft.Json.dll" "dist\"
        copy "packages\log4net.2.0.15\lib\net45\log4net.dll" "dist\"
        copy "packages\System.Net.Http.4.3.4\lib\net46\System.Net.Http.dll" "dist\"
        copy "packages\System.Configuration.ConfigurationManager.7.0.0\lib\net48\System.Configuration.ConfigurationManager.dll" "dist\"
        copy "install.bat" "dist\"
        copy "README.md" "dist\"
        copy "QUICK_START.md" "dist\"
        copy "LICENSE" "dist\"
        
    - name: Create ZIP package
      run: powershell Compress-Archive -Path 'dist\*' -DestinationPath 'PPGSage50Plugin-v1.0.0.zip' -Force
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: plugin-package
        path: PPGSage50Plugin-v1.0.0.zip
        
    - name: Create Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: PPGSage50Plugin-v1.0.0.zip
        body: |
          ## Plugin PPG Sage 50 ERP v1.0.0
          
          ### 🚀 Installation Express
          1. Télécharger `PPGSage50Plugin-v1.0.0.zip`
          2. Extraire l'archive
          3. Exécuter `install.bat` en tant qu'administrateur
          4. Configurer les credentials API PPG Live
          5. Profiter de l'intégration complète !
          
          ### 📋 Fonctionnalités
          - ✅ Synchronisation bidirectionnelle Sage 50 ↔ PPG Live
          - ✅ Gestion complète des commandes, devis, factures
          - ✅ Consultation du stock en temps réel
          - ✅ Interface utilisateur intuitive
          - ✅ Logs détaillés et monitoring
          
          ### 📖 Documentation
          - [Guide de démarrage rapide](QUICK_START.md)
          - [Documentation complète](README.md)
          - [Guide d'installation](INSTALLATION.md)
          
          ### 🆘 Support
          - Email: support.ppglive@ppg.com
          - Documentation API: https://ppglive.fr/api/docs
        draft: false
        prerelease: false
